### ISSUE TITLE
[Test Flake] E2E test can't get workflow status; problems connecting to K8s master; need longer retry window

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#169]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1109/kubeflow-presubmit/2391/?log#log

Here are the logs run run_e2e_workflow.py

[logst](https://github.com/kubeflow/testing/files/2171401/build-log.6.txt)

**Comment by jlewi** [comment]
Seeing it while polling for workflow status as well

```
INFO|2018-07-06T17:45:24|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|23| Workflow kubeflow-presubmit-kubeflow-e2e-minikube-1109-866b43a-2392-399b in namespace kubeflow-test-infra; phase=Running
WARNING|2018-07-06T17:45:24|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8aa33dd0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-tf-serving-image-1109-866b43a-2392-3fee
WARNING|2018-07-06T17:45:24|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8810fad0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-tf-serving-image-1109-866b43a-2392-3fee
WARNING|2018-07-06T17:45:24|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8810fc10>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-tf-serving-image-1109-866b43a-2392-3fee
WARNING|2018-07-06T17:45:26|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8810fe10>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7
WARNING|2018-07-06T17:45:26|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8810ff50>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7
WARNING|2018-07-06T17:45:26|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e880e20d0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7
WARNING|2018-07-06T17:45:29|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8aa03c50>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7
WARNING|2018-07-06T17:45:29|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8aa03790>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7
WARNING|2018-07-06T17:45:29|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8aa03cd0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7
ERROR|2018-07-06T17:45:29|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|211| Exception occurred: HTTPSConnectionPool(host='35.196.213.148', port=443): Max retries exceeded with url: /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8aa03750>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 197, in run
    status_callback=argo_client.log_status)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
... skipping 30 lines ...
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='35.196.213.148', port=443): Max retries exceeded with url: /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1109-866b43a-2392-cfa7 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6e8aa03750>: Failed to establish a new connection: [Errno 111] Connection refused',))
INFO|2018-07-06T17:45:29|/src/kubeflow/testing/py/kubeflow/testing/util.py|520| Writing gs://kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1109/kubeflow-presubmit/2392/finished.json
INFO|2018-07-06T17:45:29|/src/kubeflow/testing/py/kubeflow/testing/util.py|531| Uploading file /tmp/tmpRunE2eWorkflowd_ntxxlog to gs://kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1109/kubeflow-presubmit/2392/build-log.txt.
```

It looks like the retry window is pretty short; 4 seconds.

So I think we need to do the following

1. Add exponential backoff to submission of workflows with a max retry window of O(minutes)
1. Add exponential backoff to get workflow status with a max retry window of O(minutes)

**Comment by jlewi** [comment]
Still seeing test flakes even with longer timeout.
In kubeflow/kubeflow#1133; we were retrying for 4 minutes and it still failed.

Stack trace is:

```
Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 197, in run
    status_callback=argo_client.log_status)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
... skipping 30 lines ...
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
```

Error is 

```
WARNING|2018-07-06T20:12:41|/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py|663| Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2964c0ed0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1133-dd630ff-2400-6a71
ERROR|2018-07-06T20:12:41|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|211| Exception occurred: HTTPSConnectionPool(host='35.196.213.148', port=443): Max retries exceeded with url: /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/kubeflow-presubmit-kubeflow-e2e-gke-1133-dd630ff-2400-6a71 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2964c0850>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

So the problem is we can't establish a connection to the master.

**Comment by jlewi** [comment]
Autoscaler is showing errors like the following

```
2018-07-06 20:12:55.000 UTC
Error while getting cluster status: Get https://10.39.240.1:443/api/v1/nodes: dial tcp 10.39.240.1:443: getsockopt: connection refused
```
