### ISSUE TITLE
pytests failing ImportError: No module named funcsigs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#196]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_testing/195/kubeflow-testing-presubmit/347/

```
INFO|2018-08-23T03:22:24|util.py:62| Traceback (most recent call last):
INFO|2018-08-23T03:22:25|util.py:62| File "/mnt/test-data-volume/kubeflow-testing-presubmit-unittests-195-cdae8ff-347-73c7/src/kubeflow/testing/py/kubeflow/tests/run_e2e_workflow_test.py", line 3, in <module>
INFO|2018-08-23T03:22:25|util.py:62| import mock
INFO|2018-08-23T03:22:25|util.py:62| File "/usr/local/lib/python2.7/dist-packages/mock/__init__.py", line 2, in <module>
INFO|2018-08-23T03:22:25|util.py:62| import mock.mock as _mock
INFO|2018-08-23T03:22:25|util.py:62| File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 80, in <module>
INFO|2018-08-23T03:22:25|util.py:62| import funcsigs
INFO|2018-08-23T03:22:25|util.py:62| ImportError: No module named funcsigs
INFO|2018-08-23T03:22:26|util.py:41| Running: python /mnt/test-data-volume/kubeflow-testing-presubmit-unittests-195-cdae8ff-347-73c7/src/kubeflow/testing/py/kubeflow/tests/test_util_test.py 
cwd=/mnt/test-data-volume/kubeflow-testing-presubmit-unittests-195-cdae8ff-347-73c7/src/kubeflow/testing/py/kubeflow/tests
INFO|2018-08-23T03:22:26|util.py:56| Subprocess output:
```

I just upgraded the test worker image so that could be related.

New image:
gcr.io/kubeflow-ci/test-worker:v20180822-d8bc7c8-e3b0c4 

Confirmed that in that image the import is broken.
Note its using python2.7 not python3.

**Comment by jlewi** [comment]
Lets try an earlier image:
https://pantheon.corp.google.com/gcr/images/kubeflow-ci/GLOBAL/test-worker@sha256:03f5e12edd44b85e2ec5f9cace089723886b00f53c89ab164f7b2d8277f670d9/details?tab=info

**Comment by jlewi** [comment]
gcr.io/kubeflow-ci/test-worker:v20180713-b8f1691-dirty-81baa6
import mock worked

```

```

**Comment by jlewi** [comment]
Ne image:
gcr.io/kubeflow-ci/test-worker:v20180822-da7cefc-e3b0c4

based on #195
