### ISSUE TITLE
Tests are failing because GIT_TOKEN not set

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#20]
```
INFO|2018-02-10T02:56:21|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|129| URL for workflow: http://testing-argo.kubeflow.io/timeline/kubeflow-test-infra/kubeflow-presubmit-232-a452812-181-cf21;tab=workflow
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 232, in <module>
    success = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 222, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 130, in run
    status = github_status.GithubStatus()
  File "/src/kubeflow/testing/py/kubeflow/testing/github_status.py", line 51, in __init__
    Github.__init__(self)
  File "/src/kubeflow/testing/py/kubeflow/testing/github_status.py", line 24, in __init__
    raise Exception('Missing environment variable GIT_TOKEN')
Exception: Missing environment variable GIT_TOKEN
```

This is caused by #17 . The environment variable GIT_TOKEN isn't defined in the prow job. This code runs in the prow container.

We'll need to rethink how we get the GIT API token; its possible prow attaches a secret already for the API token.

Alternatively it might just be easier to see if we can set it in the gubernator see #10 .

In the meantime we should roll this back since it breaks our tests.

@jose5918

**Comment by jlewi** [comment]
Reverted in #21.

**Comment by jose5918** [comment]
@jlewi If we move everything aside from triggering the argo test to argo will this token work? https://github.com/kubeflow/tf-operator/blob/b0561dd0b2e8254d09be71e106e2ea60727cffe9/test/workflows/components/workflows.libsonnet#L82
Also does that git token even have permission to create a status? I'll try to see if prow already has something but I suspect we shouldn't be using that their token
