### ISSUE TITLE
run_e2e_workflow.py doesn't properly handle individual workflow failures

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#260]
Here's a failed test
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_examples/446/kubeflow-examples-presubmit/1077/?log#log

Logs are here
[
[build-log (15).txt](https://github.com/kubeflow/testing/files/2713821/build-log.15.txt)

run_e2e_workflow.py aborted with the following stack trace.

```
ERROR|2018-12-28T02:23:16|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|287| Exception occurred: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 28 Dec 2018 02:23:16 GMT', 'Audit-Id': '0f9f2a94-0014-4f54-9ea7-fd1fd048afc5', 'Content-Length': '334', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"workflows.argoproj.io \"kubeflow-examples-presubmit-code-search-446-d701e99-1077-ecde\" not found","reason":"NotFound","details":{"name":"kubeflow-examples-presubmit-code-search-446-d701e99-1077-ecde","group":"argoproj.io","kind":"workflows"},"code":404}

Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 273, in run
    status_callback=argo_client.log_status)
  File "/src/kubeflow/testing/py/kubeflow/testing/argo_client.py", line 98, in wait_for_workflows
    results = get_namespaced_custom_object_with_retries(namespace, n)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/src/kubeflow/testing/py/kubeflow/testing/argo_client.py", line 70, in get_namespaced_custom_object_with_retries
    GROUP, VERSION, namespace, PLURAL, name)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 697, in get_namespaced_custom_object
    (data) = self.get_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 797, in get_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 28 Dec 2018 02:23:16 GMT', 'Audit-Id': '0f9f2a94-0014-4f54-9ea7-fd1fd048afc5', 'Content-Length': '334', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"workflows.argoproj.io \"kubeflow-examples-presubmit-code-search-446-d701e99-1077-ecde\" not found","reason":"NotFound","details":{"name":"kubeflow-examples-presubmit-code-search-446-d701e99-1077-ecde","group":"argoproj.io","kind":"workflows"},"code":404}
```

The test should be running 2 workflows. One of the workflows was successfully submitted but it looks like the other one wasn't. As a result when it tries to wait on the workflow that wasn't submitted we get a not found error.

Instead of aborting we should have marked that second workflow as a failure and continued to wait for the remaining workflows.

I think we need to fix argo_client.wait_for_workflows and have it continue to wait for workflows even if one is not found.

**Comment by jlewi** [comment]
It looks like this is still not fixed.
https://github.com/kubeflow/testing/blob/fcdd2091a95524f67aaf03b24447c97e6bc14038/py/kubeflow/testing/argo_client.py#L98

It looks like we still abort if there is a problem getting one of the workflows.
