### ISSUE TITLE
Prow jobs marked as failure even though Gubernator indicates job succeeded

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#30]
Example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_tf-operator/388/kubeflow-tf-operator-presubmit/35/

Job is marked as success and no test failures. There is no error in the log.

The issue is that the pod is exiting with non zero exit code. If we look at the pod logs (via prow jobs UI) we see the following exceptoin

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 294, in <module>
    success = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 284, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 184, in run
    if results["status"]["phase"] != "Succeeded":
TypeError: list indices must be integers, not str
```

This exception happens after the logs have been uploaded to GCS which is why it doesn't show up in the gubernator logs.

/cc @lluunn

**Comment by jlewi** [comment]
Jobs are still being reported as failed. Prow's UI changed; I can no longer see pod logs so I can't tell what the error is.

**Comment by jlewi** [comment]
There's a bug in prow causing links not to work, you can work around it by navigating to url

```
http://prow.k8s.io/log?job=<job-name-foo>&id=<build_id>
```

Same error as before

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 297, in <module>
    success = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 287, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 190, in run
    results["metadata"]["name"],
TypeError: list indices must be integers, not str
```
