### ISSUE TITLE
auto deployed kf 0.4 clusters aren't using the correct version of the code

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#315]
The https://kf-v0-4-n00.endpoints.kubeflow-ci.cloud.goog/ endpoint
Has the central dashboard failing to pull the image.
Its trying to use the image
gcr.io/kubeflow-images-public/centraldashboard:v20190222-v0.4.0-rc.1-152-g1de09b7

Which is not correct. 
It looks like this is the value on master:
https://github.com/kubeflow/kubeflow/blob/6a3c0562c4c2b31e31c849e9abcd61381f7df955/kubeflow/common/prototypes/centraldashboard.jsonnet#L6

I suspect the problem is that init.sh
https://github.com/kubeflow/testing/blob/cb2c60a869178506a7e42a79693f4f140a0c74a3/test-infra/auto-deploy/init.sh#L23

Is not correctly passing the branch to use to
https://github.com/kubeflow/testing/blob/master/test-infra/auto-deploy/checkout_lib/snapshot_kf_deployment.py

**Comment by jlewi** [comment]
With #327 most recent run of the job failed with

```
INFO|2019-03-11T00:09:39|/mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/testing/py/kubeflow/testing/util.py|71| + gcloud --project=kubeflow-ci iam service-accounts keys create /mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/kf-vmaster-n04/secrets/kf-vmaster-n04-user@kubeflow-ci.iam.gserviceaccount.com.json --iam-account kf-vmaster-n04-user@kubeflow-ci.iam.gserviceaccount.com
INFO|2019-03-11T00:09:39|/mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/testing/py/kubeflow/testing/util.py|71| ERROR: (gcloud.iam.service-accounts.keys.create) PERMISSION_DENIED: Permission iam.serviceAccountKeys.create is required to perform this operation on service account projects/-/serviceAccounts/kf-vmaster-n04-user@kubeflow-ci.iam.gserviceaccount.com.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/testing/py/kubeflow/testing/create_kf_instance.py", line 196, in <module>
    main()
  File "/mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/testing/py/kubeflow/testing/create_kf_instance.py", line 172, in main
    run_with_retry([kfctl, "apply", "platform"], cwd=app_dir, env=env)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/testing/py/kubeflow/testing/create_kf_instance.py", line 21, in run_with_retry
    util.run(*args, **kwargs)
  File "/mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/testing/py/kubeflow/testing/util.py", line 87, in run
    " ".join(command), process.returncode), "\n".join(output))
subprocess.CalledProcessError: Command 'cmd: /mnt/test-data-volume/auto_deploy/auto-deploy-v0-4-1552262400/kubeflow/scripts/kfctl.sh apply platform exited with code 1' returned non-zero exit status 1
jlewi@jlewi-carbon-glaptop:~/git_kubeflow-community$ 
```

Full log attached
[auto-deploy-v0-4-1552262400.logs.txt](https://github.com/kubeflow/testing/files/2950239/auto-deploy-v0-4-1552262400.logs.txt)

**Comment by jlewi** [comment]
Closing this as obsolete.

Lets focus on 0.5 and 0.6.
