### ISSUE TITLE
kubeflow-ci out of CPU quota and leaking clusters/deployments

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#337]
kubeflow-ci appears to be leaking test clusters causing us to run out of quota.

```
NAME              CREATE_TIME                LOCATION    STATUS
kubeflow-testing  2018-03-29T17:46:26+00:00  us-east1-d  RUNNING
kf-v0-4-n00       2019-02-27T00:08:08+00:00  us-east1-d  RUNNING
kf-v0-4-n01       2019-02-27T12:06:07+00:00  us-east1-d  RUNNING
kf-v0-4-n04       2019-03-01T01:26:22+00:00  us-east1-d  RUNNING
kf-vmaster-n00    2019-03-25T00:25:51+00:00  us-east1-b  RUNNING
kf-vmaster-n01    2019-03-25T12:31:04+00:00  us-east1-b  RUNNING
kfctl-473b        2019-03-25T21:31:32+00:00  us-east1-d  RUNNING
kfctl-99b3        2019-03-25T22:04:56+00:00  us-east1-d  RUNNING
kf-v0-4-n02       2019-03-25T22:05:41+00:00  us-east1-d  RUNNING
kf-v0-4-n03       2019-03-25T22:10:08+00:00  us-east1-d  RUNNING
kfctl-14c4        2019-03-25T22:43:06+00:00  us-east1-d  RUNNING
kf-vmaster-n02    2019-03-26T00:20:36+00:00  us-east1-b  RUNNING
kfctl-4914        2019-03-26T06:06:58+00:00  us-east1-d  RUNNING
kfctl-1d67        2019-03-26T15:24:54+00:00  us-east1-d  RUNNING

```
Some of these clusters like `kfctl-473b` is over a 24 hours old. So it should have been GC'd by the cron job.

The kubeflow-testing cluster is also using 15 nodes and 120 CPUs. That seems like a lot.

**Comment by jlewi** [comment]
It doesn't look like our cron job to cleanup the ci system is configured.

```
kubectl get cronjobs
NAME                 SCHEDULE       SUSPEND   ACTIVE    LAST SCHEDULE   AGE
auto-deploy-master   0 */12 * * *   False     0         3h              17d
auto-deploy-v0-4     0 */12 * * *   False     0         3h              17d
```

**Comment by jlewi** [comment]
Started the cronjob.

```
kubectl get cronjobs
NAME                 SCHEDULE       SUSPEND   ACTIVE    LAST SCHEDULE   AGE
auto-deploy-master   0 */12 * * *   False     0         3h              17d
auto-deploy-v0-4     0 */12 * * *   False     0         3h              17d
cleanup-ci           0 */2 * * *    False     0         <none>          10s
jlewi@jlewi-carbon-glaptop:~/git_kubeflow-testing/test-infra/ks_app$ ks apply
```

**Comment by jlewi** [comment]
Started a oneoff run of the ci job.

**Comment by jlewi** [comment]
The cleanup job is failing with a connection error trying to call delete on DM.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 382, in <module>
    main()
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 379, in main
    args.func(args)
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 297, in cleanup_all
    cleanup_deployments(args)
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 226, in cleanup_deployments
    project=args.project, deployment=name, manifest=manifest_name).execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 839, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 166, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1355, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
```
