### ISSUE TITLE
HTTP errors getting workflow status prevent status from being recorded

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#386]
Here's a test run where the test aborted due to an exception caused by an HTTP error getting workflow status
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3208/kubeflow-presubmit/1126233582973489152/

* The workflow status isn't reported and no yaml files for the Argo workflows are uploaded

Here are the full logs
[build-log (12).txt](https://github.com/kubeflow/testing/files/3162568/build-log.12.txt)

The exception is as follows

```
ERROR|2019-05-08T21:43:23|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|296| Exception occurred: (504)
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 08 May 2019 21:43:23 GMT', 'Content-Length': '136', 'Content-Type': 'text/plain; charset=utf-8'})
HTTP response body: {"metadata":{},"status":"Failure","message":"Timeout: request did not complete within 1m0s","reason":"Timeout","details":{},"code":504}

Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 276, in run
    status_callback=argo_client.log_status
  File "/src/kubeflow/testing/py/kubeflow/testing/argo_client.py", line 101, in wait_for_workflows
    results = get_namespaced_custom_object_with_retries(namespace, n)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/src/kubeflow/testing/py/kubeflow/testing/argo_client.py", line 70, in get_namespaced_custom_object_with_retries
    GROUP, VERSION, namespace, PLURAL, name)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 697, in get_namespaced_custom_object
    (data) = self.get_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 797, in get_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
ApiException: (504)
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 08 May 2019 21:43:23 GMT', 'Content-Length': '136', 'Content-Type': 'text/plain; charset=utf-8'})
HTTP response body: {"metadata":{},"status":"Failure","message":"Timeout: request did not complete within 1m0s","reason":"Timeout","details":{},"code":504}
```

So the argo client gets a 504 error trying to talk to K8s APIServer to get workflow status. Even though we have retries it looks like those retries are expiring.

[get_namespaced_custom_object](https://github.com/kubeflow/testing/blob/dff7bf095f45d2089f3a40217b1c9deca9ad8f27/py/kubeflow/testing/argo_client.py#L55) should be retrying for up to 5 minutes. But it looks like we don't treat a 504 as a retryable error
https://github.com/kubeflow/testing/blob/dff7bf095f45d2089f3a40217b1c9deca9ad8f27/py/kubeflow/testing/argo_client.py#L34

The log messages indicate about 5 minutes elapse in between last successful call to get status as well as the timeout.

I suspect the delay is in the k8s client waiting to timeout.

The other problem is that since wait_for_workflows aborts with an exception we don't end up reporting the status and uploading yaml specs for the workflows in run_e2e_workflow.py

So I think we want to make 2 fixes.

* Add 504 to set of APIGateway exceptions we retry on here
  https://github.com/kubeflow/testing/blob/dff7bf095f45d2089f3a40217b1c9deca9ad8f27/py/kubeflow/testing/argo_client.py#L34

* [WaitForWorkflows](https://github.com/kubeflow/testing/blob/dff7bf095f45d2089f3a40217b1c9deca9ad8f27/py/kubeflow/testing/argo_client.py#L100) should catch exceptions and reraise the exception appending the most recent set of results
  * In the [exception handling](https://github.com/kubeflow/testing/blob/dff7bf095f45d2089f3a40217b1c9deca9ad8f27/py/kubeflow/testing/run_e2e_workflow.py#L292) for wait_for_workflows we should extract results from the exception and use them to report status

**Comment by derekhh** [comment]
@jlewi - I'll take a look and fix it :)
