### ISSUE TITLE
prow for kubeflow components cannot work now

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/testing#417]
When create a PR in kubeflow repo (you can check any latest PR of kubeflow repo, saying katib, kfserving etc.), prow job always fail with below message
```
INFO|2019-07-11T10:33:26|/src/kubeflow/testing/py/kubeflow/testing/util.py|60| Subprocess output:
INFO|2019-07-11T10:33:26|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=info msg="setting environment component" component-name=workflows-v1alpha1
INFO|2019-07-11T10:33:27|/src/kubeflow/testing/py/kubeflow/testing/util.py|45| Running: ks param set --env=kubeflow-katib-presubmit-e2e-v1alpha1-682-3b8a9c1-0368-5b12 workflows-v1alpha1 registry gcr.io/kubeflow-ci 
cwd=/src/kubeflow/katib/test/workflows
INFO|2019-07-11T10:33:27|/src/kubeflow/testing/py/kubeflow/testing/util.py|60| Subprocess output:
INFO|2019-07-11T10:33:27|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=info msg="setting environment component" component-name=workflows-v1alpha1
INFO|2019-07-11T10:33:28|/src/kubeflow/testing/py/kubeflow/testing/util.py|45| Running: ks show kubeflow-katib-presubmit-e2e-v1alpha1-682-3b8a9c1-0368-5b12 -c workflows-v1alpha1 
cwd=/src/kubeflow/katib/test/workflows
INFO|2019-07-11T10:33:28|/src/kubeflow/testing/py/kubeflow/testing/util.py|60| Subprocess output:
INFO|2019-07-11T10:33:28|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=error msg="find objects: Received status code '404' when trying to retrieve OpenAPI schema for cluster version 'v0.3.1' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v0.3.1/api/openapi-spec/swagger.json'"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 417, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 407, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 273, in run
    util.run([ks_cmd, "show", env, "-c", w.component], cwd=w.app_dir)
  File "/src/kubeflow/testing/py/kubeflow/testing/util.py", line 87, in run
    " ".join(command), process.returncode), "\n".join(output))
subprocess.CalledProcessError: Command 'cmd: ks show kubeflow-katib-presubmit-e2e-v1alpha1-682-3b8a9c1-0368-5b12 -c workflows-v1alpha1 exited with code 1' returned non-zero exit status 1
```

refer more to below example links
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_fairing/311/kubeflow-fairing-presubmit/1148823530889023488/
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kfserving/232/kubeflow-kfserving-presubmit/1148822650630443011/

**Comment by jlewi** [comment]
@hougangliu Is the URL  https://raw.githubusercontent.com/kubernetes/kubernetes/v0.3.1/api/openapi-spec/swagger.json available?

**Comment by jlewi** [comment]
@karthikv2k I believe you fixed this at least for some repos? I think the fix was upgrading? Can you explain what you did to fix it?

**Comment by hougangliu** [comment]
https://github.com/kubeflow/kfserving/pull/239/files
changing apiVersion from 0.1.0 to 0.3.0 as below make this issue gone
```
apiVersion: 0.3.0
environments:
  releasing:
    destination:
      namespace: kubeflow-releasing
      server: https://35.226.49.107
    k8sVersion: v1.7.0
    path: releasing
kind: ksonnet.io/app
name: worfklows-app
version: 0.0.1
```

**Comment by karthikv2k** [comment]
Yes upgrading apiversion fixed the bug.

**Comment by jlewi** [comment]
Thanks closing this bug.
