### ISSUE TITLE
kubeflow-ci-deployment out of private address space on default network

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#480]
Starting to see this area again.

#476 was the previous instance of this issue.

It does look like we are leaking some clusters

```
gcloud --project=kubeflow-ci-deployment container clusters list --format="table(name, location, status, createTime)" --sort-by=createTime
NAME            LOCATION       STATUS        CREATE_TIME
deployapp       us-east1-d     RUNNING       2019-04-26T22:35:53+00:00
apps            us-central1-a  RUNNING       2019-09-18T23:04:32+00:00
kf-vmaster-n04  us-east1-b     RUNNING       2019-10-02T12:13:19+00:00
kf-vmaster-n00  us-east1-b     RUNNING       2019-10-03T00:09:58+00:00
myapp2          us-central1-a  RUNNING       2019-10-03T04:18:04+00:00
kf-vmaster-n01  us-east1-b     RUNNING       2019-10-03T12:12:28+00:00
kf-vmaster-n02  us-east1-b     RUNNING       2019-10-04T00:12:04+00:00
kfctl-e899      us-central1-a  RUNNING       2019-10-09T05:50:58+00:00
kfctl-f766      us-central1-a  RUNNING       2019-10-10T01:57:22+00:00
kfctl-d643      us-central1-a  RUNNING       2019-10-10T23:53:57+00:00
kfctl-f282      us-central1-a  RUNNING       2019-10-11T23:19:33+00:00
kfctl-d448      us-central1-a  RUNNING       2019-10-11T23:28:00+00:00
kfctl-f5dc      us-central1-a  RUNNING       2019-10-12T01:55:03+00:00
kfctl-e1d5      us-central1-a  RUNNING       2019-10-12T06:56:23+00:00
kf-v0-6-n04     us-east1-b     RUNNING       2019-10-12T12:30:23+00:00
kfctl-d472      us-central1-a  RUNNING       2019-10-12T23:23:27+00:00
kf-v0-6-n00     us-east1-b     RUNNING       2019-10-13T00:21:04+00:00
kf-v0-6-n01     us-east1-b     RUNNING       2019-10-13T12:15:05+00:00
kf-v0-6-n02     us-east1-b     RUNNING       2019-10-14T00:15:11+00:00
kfctl-d256      us-central1-a  RUNNING       2019-10-14T07:48:46+00:00
kf-v0-6-n03     us-east1-b     RUNNING       2019-10-14T12:16:20+00:00
kfctl-d9fd      us-central1-a  ERROR         2019-10-14T18:15:43+00:00
kfctl-d5ee      us-central1-a  ERROR         2019-10-14T18:22:37+00:00
kfctl-f25a      us-central1-a  ERROR         2019-10-14T18:23:33+00:00
kfctl-8625      us-central1-a  ERROR         2019-10-14T20:26:18+00:00
kfctl-aeb1      us-central1-a  ERROR         2019-10-14T20:26:31+00:00
kfctl-249a      us-central1-a  ERROR         2019-10-14T20:26:59+00:00
kfctl-6d9c      us-central1-a  ERROR         2019-10-14T20:27:02+00:00
kfctl-aa57      us-central1-a  STOPPING      2019-10-14T21:00:59+00:00
kfctl-64d5      us-central1-a  RUNNING       2019-10-14T21:06:19+00:00
kfctl-3c2b      us-central1-a  RUNNING       2019-10-14T21:06:48+00:00
kfctl-c3c3      us-central1-a  PROVISIONING  2019-10-14T21:08:13+00:00
kfctl-0cea      us-central1-a  RUNNING       2019-10-14T21:08:45+00:00
kfctl-3325      us-central1-a  RUNNING       2019-10-14T21:09:44+00:00
```

**Comment by jlewi** [comment]
Here are the logs from the most recent run
[cleanup-kubeflow-ci-deployment.txt](https://github.com/kubeflow/testing/files/3726517/cleanup-kubeflow-ci-deployment.txt)

It looks like it was in the process of deleting clusters when it hit the following error

```
ERROR|2019-10-14T20:12:13|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|943| Command '['/src/kubeflow/kubeflow/scripts/gke/delete_deployment.sh', '--project=kubeflow-ci-deployment', u'--deployment=kfctl-d224', '--zone=']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 941, in cleanup_all
    op(args)
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 880, in cleanup_deployments
    subprocess.check_call(command, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/src/kubeflow/kubeflow/scripts/gke/delete_deployment.sh', '--project=kubeflow-ci-deployment', u'--deployment=kfctl-d224', '--zone=']' returned non-zero exit status 1
INFO|2019-10-14T20:12:13|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|110| Cleanup Google Cloud Endpoints
WARNING|2019-10-14T20:12:13|/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py|44| file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
```

**Comment by jlewi** [comment]
The current time is 2019-10-14T22:05

We GC deployments after 3 hours. So anything before 2019-10-14T19:05 should be expired. It looks like we have a couple of those.

Deployments in an error state should also be aggressively pruned after 10 minutes.

I triggered a oneoff job based on #481. Hopefully that prevents the exception which is causing to abort before properly GC'ing all the clusters.

```
gcloud --project=kubeflow-ci-deployment container clusters list --format="table(name, location, status, createTime)" --sort-by=createTime
NAME            LOCATION       STATUS   CREATE_TIME
deployapp       us-east1-d     RUNNING  2019-04-26T22:35:53+00:00
apps            us-central1-a  RUNNING  2019-09-18T23:04:32+00:00
kf-vmaster-n04  us-east1-b     RUNNING  2019-10-02T12:13:19+00:00
kf-vmaster-n00  us-east1-b     RUNNING  2019-10-03T00:09:58+00:00
myapp2          us-central1-a  RUNNING  2019-10-03T04:18:04+00:00
kf-vmaster-n01  us-east1-b     RUNNING  2019-10-03T12:12:28+00:00
kf-vmaster-n02  us-east1-b     RUNNING  2019-10-04T00:12:04+00:00
kfctl-e899      us-central1-a  RUNNING  2019-10-09T05:50:58+00:00
kfctl-f766      us-central1-a  RUNNING  2019-10-10T01:57:22+00:00
kfctl-d643      us-central1-a  RUNNING  2019-10-10T23:53:57+00:00
kfctl-f282      us-central1-a  RUNNING  2019-10-11T23:19:33+00:00
kfctl-d448      us-central1-a  RUNNING  2019-10-11T23:28:00+00:00
kfctl-f5dc      us-central1-a  RUNNING  2019-10-12T01:55:03+00:00
kfctl-e1d5      us-central1-a  RUNNING  2019-10-12T06:56:23+00:00
kf-v0-6-n04     us-east1-b     RUNNING  2019-10-12T12:30:23+00:00
kfctl-d472      us-central1-a  RUNNING  2019-10-12T23:23:27+00:00
kf-v0-6-n00     us-east1-b     RUNNING  2019-10-13T00:21:04+00:00
kf-v0-6-n01     us-east1-b     RUNNING  2019-10-13T12:15:05+00:00
kf-v0-6-n02     us-east1-b     RUNNING  2019-10-14T00:15:11+00:00
kfctl-d256      us-central1-a  RUNNING  2019-10-14T07:48:46+00:00
kf-v0-6-n03     us-east1-b     RUNNING  2019-10-14T12:16:20+00:00
kfctl-d9fd      us-central1-a  ERROR    2019-10-14T18:15:43+00:00
kfctl-d5ee      us-central1-a  ERROR    2019-10-14T18:22:37+00:00
kfctl-f25a      us-central1-a  ERROR    2019-10-14T18:23:33+00:00
kfctl-8625      us-central1-a  ERROR    2019-10-14T20:26:18+00:00
kfctl-aeb1      us-central1-a  ERROR    2019-10-14T20:26:31+00:00
kfctl-6d9c      us-central1-a  ERROR    2019-10-14T20:27:02+00:00
kfctl-370c      us-central1-a  ERROR    2019-10-14T21:19:41+00:00
kfctl-373f      us-central1-a  ERROR    2019-10-14T21:20:38+00:00
kfctl-dabe      us-central1-a  ERROR    2019-10-14T21:22:07+00:00
kfctl-f1cc      us-central1-a  ERROR    2019-10-14T21:22:26+00:00
kfctl-62b8      us-central1-a  ERROR    2019-10-14T21:22:56+00:00
kfctl-feb7      us-central1-a  ERROR    2019-10-14T21:24:44+00:00
kfctl-f645      us-central1-a  ERROR    2019-10-14T21:24:49+00:00
kfctl-bc84      us-central1-a  ERROR    2019-10-14T21:31:25+00:00
kfctl-9199      us-central1-a  ERROR    2019-10-14T21:31:44+00:00
kfctl-39e5      us-central1-a  ERROR    2019-10-14T21:33:57+00:00
kfctl-056a      us-central1-a  RUNNING  2019-10-14T21:49:17+00:00
kfctl-6d5b      us-central1-a  RUNNING  2019-10-14T21:52:46+00:00
kfctl-398b      us-central1-a  RUNNING  2019-10-14T21:54:38+00:00
kfctl-c3c4      us-central1-a  RUNNING  2019-10-14T21:54:54+00:00
kfctl-56bc      us-central1-a  RUNNING  2019-10-14T21:55:24+00:00
```

**Comment by jlewi** [comment]
On my one off job it aborted with error

```
+ echo 'Usage: delete_deployment --project=PROJECT --deployment=DEPLOYMENT_NAME --zone=ZONE'
+ exit 1
Usage: delete_deployment --project=PROJECT --deployment=DEPLOYMENT_NAME --zone=ZONE
ERROR|2019-10-14T22:27:38|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|944| Command '['/src/kubeflow/kubeflow/scripts/gke/delete_deployment.sh', '--project=kubeflow-ci-deployment', u'--deployment=kfctl-d224', '--zone=']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 942, in cleanup_all
    op(args)
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 881, in cleanup_deployments
    subprocess.check_call(command, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/src/kubeflow/kubeflow/scripts/gke/delete_deployment.sh', '--project=kubeflow-ci-deployment', u'--deployment=kfctl-d224', '--zone=']' returned non-zero exit status 1
INFO|2019-10-14T22:27:38|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|110| C
```

**Comment by jlewi** [comment]
```
gcloud --project=kubeflow-ci-deployment container clusters list --format="table(name, location, status, createTime)" --sort-by=createTime
NAME            LOCATION       STATUS   CREATE_TIME
deployapp       us-east1-d     RUNNING  2019-04-26T22:35:53+00:00
apps            us-central1-a  RUNNING  2019-09-18T23:04:32+00:00
kf-vmaster-n04  us-east1-b     RUNNING  2019-10-02T12:13:19+00:00
kf-vmaster-n00  us-east1-b     RUNNING  2019-10-03T00:09:58+00:00
myapp2          us-central1-a  RUNNING  2019-10-03T04:18:04+00:00
kf-vmaster-n01  us-east1-b     RUNNING  2019-10-03T12:12:28+00:00
kf-vmaster-n02  us-east1-b     RUNNING  2019-10-04T00:12:04+00:00
kfctl-e899      us-central1-a  RUNNING  2019-10-09T05:50:58+00:00
kfctl-f766      us-central1-a  RUNNING  2019-10-10T01:57:22+00:00
kfctl-d643      us-central1-a  RUNNING  2019-10-10T23:53:57+00:00
kfctl-f282      us-central1-a  RUNNING  2019-10-11T23:19:33+00:00
kfctl-f5dc      us-central1-a  RUNNING  2019-10-12T01:55:03+00:00
kfctl-e1d5      us-central1-a  RUNNING  2019-10-12T06:56:23+00:00
kfctl-d472      us-central1-a  RUNNING  2019-10-12T23:23:27+00:00
kf-v0-6-n00     us-east1-b     RUNNING  2019-10-13T00:21:04+00:00
kf-v0-6-n01     us-east1-b     RUNNING  2019-10-13T12:15:05+00:00
kf-v0-6-n02     us-east1-b     RUNNING  2019-10-14T00:15:11+00:00
kf-v0-6-n03     us-east1-b     RUNNING  2019-10-14T12:16:20+00:00
kfctl-d9fd      us-central1-a  ERROR    2019-10-14T18:15:43+00:00
kfctl-d5ee      us-central1-a  ERROR    2019-10-14T18:22:37+00:00
kfctl-f25a      us-central1-a  ERROR    2019-10-14T18:23:33+00:00
kfctl-dabe      us-central1-a  ERROR    2019-10-14T21:22:07+00:00
kfctl-f1cc      us-central1-a  ERROR    2019-10-14T21:22:26+00:00
kfctl-feb7      us-central1-a  ERROR    2019-10-14T21:24:44+00:00
kfctl-f645      us-central1-a  ERROR    2019-10-14T21:24:49+00:00
kfctl-dece      us-central1-a  ERROR    2019-10-14T22:33:25+00:00
kfctl-21e7      us-central1-a  ERROR    2019-10-15T00:21:04+00:00
kf-v0-6-n04     us-east1-b     RUNNING  2019-10-15T00:35:00+00:00
kfctl-ef3c      us-central1-a  RUNNING  2019-10-15T01:02:26+00:00
```

**Comment by jlewi** [comment]
All the error clusters and old clusters have been GC'd.

```
gcloud --project=kubeflow-ci-deployment container clusters list --format="table(name, location, status, createTime)" --sort-by=createTime
NAME            LOCATION       STATUS    CREATE_TIME
deployapp       us-east1-d     RUNNING   2019-04-26T22:35:53+00:00
apps            us-central1-a  RUNNING   2019-09-18T23:04:32+00:00
kf-vmaster-n04  us-east1-b     RUNNING   2019-10-02T12:13:19+00:00
kf-vmaster-n00  us-east1-b     RUNNING   2019-10-03T00:09:58+00:00
myapp2          us-central1-a  RUNNING   2019-10-03T04:18:04+00:00
kf-vmaster-n01  us-east1-b     RUNNING   2019-10-03T12:12:28+00:00
kf-vmaster-n02  us-east1-b     RUNNING   2019-10-04T00:12:04+00:00
kf-v0-6-n00     us-east1-b     RUNNING   2019-10-13T00:21:04+00:00
kf-v0-6-n01     us-east1-b     RUNNING   2019-10-13T12:15:05+00:00
kf-v0-6-n02     us-east1-b     RUNNING   2019-10-14T00:15:11+00:00
kf-v0-6-n03     us-east1-b     RUNNING   2019-10-14T12:16:20+00:00
kfctl-21e7      us-central1-a  ERROR     2019-10-15T00:21:04+00:00
kf-v0-6-n04     us-east1-b     RUNNING   2019-10-15T00:35:00+00:00
kfctl-0dca      us-central1-a  RUNNING   2019-10-15T02:23:32+00:00
kfctl-9fe7      us-central1-a  STOPPING  2019-10-15T02:23:58+00:00
kfctl-0b24      us-central1-a  RUNNING   2019-10-15T02:28:29+00:00
kfctl-ec12      us-central1-a  RUNNING   2019-10-15T02:28:46+00:00
kfctl-03de      us-central1-a  RUNNING   2019-10-15T02:29:20+00:00
kfctl-5b23      us-central1-a  RUNNING   2019-10-15T02:29:28+00:00

```

**Comment by jlewi** [comment]
We can close this when the PR is merged.

**Comment by jlewi** [comment]
Out of space again

```
gcloud --project=kubeflow-ci-deployment container clusters list --format="table(name, location, status, createTime)" --sort-by=createTime
NAME            LOCATION       STATUS        CREATE_TIME
deployapp       us-east1-d     RUNNING       2019-04-26T22:35:53+00:00
apps            us-central1-a  RUNNING       2019-09-18T23:04:32+00:00
kf-vmaster-n04  us-east1-b     RUNNING       2019-10-02T12:13:19+00:00
kf-vmaster-n00  us-east1-b     RUNNING       2019-10-03T00:09:58+00:00
myapp2          us-central1-a  RUNNING       2019-10-03T04:18:04+00:00
kf-vmaster-n01  us-east1-b     RUNNING       2019-10-03T12:12:28+00:00
kf-vmaster-n02  us-east1-b     RUNNING       2019-10-04T00:12:04+00:00
kf-v0-6-n01     us-east1-b     RUNNING       2019-10-13T12:15:05+00:00
kf-v0-6-n02     us-east1-b     RUNNING       2019-10-14T00:15:11+00:00
kf-v0-6-n03     us-east1-b     RUNNING       2019-10-14T12:16:20+00:00
kf-v0-6-n04     us-east1-b     RUNNING       2019-10-15T00:35:00+00:00
kf-v0-6-n00     us-east1-b     RUNNING       2019-10-15T12:22:50+00:00
kfctl-7680      us-central1-a  RUNNING       2019-10-15T17:27:49+00:00
kfctl-f71b      us-central1-a  RUNNING       2019-10-15T17:27:56+00:00
kfctl-93f7      us-central1-a  RUNNING       2019-10-15T17:29:49+00:00
kfctl-73a4      us-central1-a  STOPPING      2019-10-15T18:24:01+00:00
kfctl-bca7      us-central1-a  RUNNING       2019-10-15T18:50:30+00:00
kfctl-8140      us-central1-a  RUNNING       2019-10-15T18:51:03+00:00
kfctl-3a08      us-central1-a  STOPPING      2019-10-15T18:51:51+00:00
kfctl-1cef      us-central1-a  RUNNING       2019-10-15T19:39:38+00:00
kfctl-9f56      us-central1-a  RUNNING       2019-10-15T19:40:45+00:00
kfctl-3778      us-central1-a  RUNNING       2019-10-15T19:40:47+00:00
kfctl-1fd6      us-central1-a  RUNNING       2019-10-15T19:41:31+00:00
kfctl-0e66      us-central1-a  RUNNING       2019-10-15T20:38:44+00:00
kfctl-530f      us-central1-a  RUNNING       2019-10-15T20:39:16+00:00
kfctl-2130      us-central1-a  RUNNING       2019-10-15T20:39:32+00:00
kfctl-8544      us-central1-a  RUNNING       2019-10-15T20:39:32+00:00
kfctl-bd1c      us-central1-a  ERROR         2019-10-15T21:09:20+00:00
kfctl-d45e      us-central1-a  ERROR         2019-10-15T21:09:35+00:00
kfctl-0733      us-central1-a  ERROR         2019-10-15T21:11:00+00:00
kfctl-ea49      us-central1-a  RUNNING       2019-10-15T21:29:15+00:00
kfctl-01c3      us-central1-a  RUNNING       2019-10-15T21:29:52+00:00
kfctl-79d4      us-central1-a  ERROR         2019-10-15T21:30:01+00:00
kfctl-9a74      us-central1-a  ERROR         2019-10-15T21:30:37+00:00
kfctl-816c      us-central1-a  ERROR         2019-10-15T21:30:43+00:00
kfctl-c806      us-central1-a  ERROR         2019-10-15T21:30:49+00:00
kfctl-2b30      us-central1-a  ERROR         2019-10-15T21:31:16+00:00
kfctl-9e78      us-central1-a  ERROR         2019-10-15T21:55:37+00:00
kfctl-4732      us-central1-a  ERROR         2019-10-15T21:55:54+00:00
kfctl-8776      us-central1-a  ERROR         2019-10-15T21:56:18+00:00
kfctl-7595      us-central1-a  ERROR         2019-10-15T21:56:33+00:00
kfctl-b308      us-central1-a  ERROR         2019-10-15T21:57:02+00:00
kfctl-ff9a      us-central1-a  ERROR         2019-10-15T21:57:50+00:00
kfctl-d834      us-central1-a  ERROR         2019-10-15T21:58:45+00:00
kfctl-cc73      us-central1-a  ERROR         2019-10-15T22:00:42+00:00
kfctl-c994      us-central1-a  ERROR         2019-10-15T22:01:20+00:00
kfctl-c6c4      us-central1-a  ERROR         2019-10-15T22:03:33+00:00
kfctl-617e      us-central1-a  ERROR         2019-10-15T22:04:09+00:00
kfctl-f206      us-central1-a  ERROR         2019-10-15T22:04:24+00:00
kfctl-cba4      us-central1-a  ERROR         2019-10-15T22:04:33+00:00
kfctl-4a1a      us-central1-a  ERROR         2019-10-15T22:05:16+00:00
kfctl-d22c      us-central1-a  ERROR         2019-10-15T22:06:02+00:00
kfctl-f39f      us-central1-a  ERROR         2019-10-15T22:06:23+00:00
kfctl-b5fe      us-central1-a  STOPPING      2019-10-15T22:08:59+00:00
kfctl-cb76      us-central1-a  ERROR         2019-10-15T22:10:30+00:00
kfctl-1990      us-central1-a  ERROR         2019-10-15T22:14:17+00:00
kfctl-895e      us-central1-a  PROVISIONING  2019-10-15T22:21:32+00:00
kfctl-9e45      us-central1-a  ERROR         2019-10-15T22:21:34+00:00
kfctl-193e      us-central1-a  ERROR         2019-10-15T22:23:05+00:00
kfctl-36e1      us-central1-a  ERROR         2019-10-15T22:23:09+00:00

```

**Comment by jlewi** [comment]
Seeing errors like

```
INFO|2019-10-15T22:42:40|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|835| Deployment kfctl-b308 has expired
INFO|2019-10-15T22:42:40|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|837| Deleting deployment kfctl-b308
INFO|2019-10-15T22:42:40|/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py|866| URL being requested: DELETE https://www.googleapis.com/deploymentmanager/v2/projects/kubeflow-ci-deployment/global/deployments/kfctl-b308?alt=json
ERROR|2019-10-15T22:42:40|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|847| There was a problem deleting deployment kfctl-b308; error <HttpError 404 when requesting https://www.googleapis.com/deploymentmanager/v2/projects/kubeflow-ci-deployment/global/deployments/kfctl-b308?alt=json returned "The object 'projects/kubeflow-ci-deployment/global/deployments/kfctl-b308' is not found.">

```

**Comment by jlewi** [comment]
```
gcloud --project=kubeflow-ci deployment-manager deployments list --format="table(name,insertTime:sort=1)" 
NAME                       INSERT_TIME
devstats                   2018-04-26T05:34:35.326-07:00
param-test-storage         2019-02-26T12:44:50.934-08:00
kf-vmaster-n00-storage     2019-04-02T05:14:32.668-07:00
kf-vmaster-n00             2019-04-02T05:14:48.514-07:00
kubeflow-ci-fairing        2019-04-22T14:55:34.124-07:00
kubeflow-fairing1-storage  2019-08-22T22:51:28.312-07:00
kubeflow-fairing1          2019-08-22T22:51:28.637-07:00
kubeflow-ci-nfs            2019-10-02T15:20:15.954-07:00
```

**Comment by jlewi** [comment]
It looks like we are not aggressively pruning clusters in the error state.

**Comment by jlewi** [comment]
We should be healthy again.

```
gcloud --project=kubeflow-ci-deployment container clusters list --format="table(name, location, status, createTime)" --sort-by=createTime
NAME            LOCATION       STATUS    CREATE_TIME
deployapp       us-east1-d     RUNNING   2019-04-26T22:35:53+00:00
apps            us-central1-a  RUNNING   2019-09-18T23:04:32+00:00
kf-vmaster-n04  us-east1-b     RUNNING   2019-10-02T12:13:19+00:00
kf-vmaster-n00  us-east1-b     RUNNING   2019-10-03T00:09:58+00:00
myapp2          us-central1-a  RUNNING   2019-10-03T04:18:04+00:00
kf-vmaster-n01  us-east1-b     RUNNING   2019-10-03T12:12:28+00:00
kf-vmaster-n02  us-east1-b     RUNNING   2019-10-04T00:12:04+00:00
kf-v0-6-n01     us-east1-b     RUNNING   2019-10-13T12:15:05+00:00
kf-v0-6-n02     us-east1-b     RUNNING   2019-10-14T00:15:11+00:00
kf-v0-6-n03     us-east1-b     RUNNING   2019-10-14T12:16:20+00:00
kf-v0-6-n04     us-east1-b     RUNNING   2019-10-15T00:35:00+00:00
kf-v0-6-n00     us-east1-b     RUNNING   2019-10-15T12:22:50+00:00
kfctl-0e66      us-central1-a  STOPPING  2019-10-15T20:38:44+00:00
kfctl-2130      us-central1-a  STOPPING  2019-10-15T20:39:32+00:00

```
