### ISSUE TITLE
Workload identity not working TF; kubeflow-ci-deployment.svc.id.goog with additional claims does not have storage.objects.get access

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#499]
In the kubeflow/example mnist CI/CD tests is failed caused by beflow issue,

1. using the cluster `kf-vmaster-n01`. 
2. Found this try to resolve other porblem in the PR https://github.com/kubeflow/examples/pull/668.

```
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
Train and evaluate
Traceback (most recent call last):
 File "/opt/model.py", line 233, in <module>
   tf.app.run()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
   _sys.exit(main(argv))
 File "/opt/model.py", line 224, in main
   tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
   executor.run()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run
   getattr(self, task_to_run)()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 551, in run_chief
   return self._start_distributed_training()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 739, in _start_distributed_training
   saving_listeners=saving_listeners)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 355, in train
   loss = self._train_model(input_fn, hooks, saving_listeners)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 900, in _train_model
   log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
   stop_grace_period_secs=stop_grace_period_secs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 795, in __init__
   stop_grace_period_secs=stop_grace_period_secs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 511, in __init__
   h.begin()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 424, in begin
   self._summary_writer = SummaryWriterCache.get(self._checkpoint_dir)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/writer_cache.py", line 63, in get
   logdir, graph=ops.get_default_graph())
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/writer.py", line 352, in __init__
   filename_suffix)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/event_file_writer.py", line 67, in __init__
   gfile.MakeDirs(self._logdir)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 374, in recursive_create_dir
   pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
   c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request (HTTP response code 403, error code 0, err
or message ''), response '{
 "error": {
   "code": 403,
   "message": "Primary: /namespaces/kubeflow-ci-deployment.svc.id.goog with additional claims does not have storage.objects.get access to
 kubeflow-ci-deployment_ci-temp/mnist/models/1186838838111113219.",
   "errors": [
     {
       "message": "Primary: /namespaces/kubeflow-ci-deployment.svc.id.goog with additional claims does not have storage.objects.get acces
s to kubeflow-ci-deployment_ci-temp/mnist/models/1186838838111113219.",
       "domain": "global",
'
         when reading metadata of gs://kubeflow-ci-deployment_ci-temp/mnist/models/1186838838111113219
```

**Comment by jlewi** [comment]
This looks like an issue with workload identity, TF, and GCS. I'm not sure where the error lies; i.e.

* Is workload identity misconfigured?
* Is there an issue with TF code and workload identity?
* Are IAM permissions misconfigured?

I checked kf-vmaster-n01 it looks like it is pined to the correct version of GKE

```
kf-vmaster-n01       us-east1-b     RUNNING  2019-10-03T12:12:28+00:00
```

To avoid the bug we encountered with workload identity on later versions of 1.14.

This cluster looks quite old; created on 2019-10-03. So I suspect there are multiple bugs with workload identity.

It doesn't look like the default-editor account is bound to a service account

```
```

**Comment by jinchihe** [comment]
@jlewi Thanks Jeremy, i do not think that's caused by workflow issue. I just updated the test cluster to `kf-v0-6-n00`, that's OK. checked the version of `kf-v0-6-n00` is `1.12.10-gke.15` and `kf-vmaster-n00` version is `1.14.6-gke.2`. I do not know any other difference.

**Comment by jinchihe** [comment]
> I'm assuming perhaps incorrectly, that the sample has been updated to use workload identity. Is the pod still setting GOOGLE_APPLICATION_CREDENTIALS and trying to mount the user-gcp-sa secret?

Yes, I think so, that may be caused by workload identity.

**Comment by jinchihe** [comment]
The problem cannot be reproduced after refactor the CI tests. Closing the issue.
