### ISSUE TITLE
prow dashboard doesn't show the test is finished

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/testing#542]
this happens in periodic tests.  in artifacts it doesn't have quite a few files, including `finished.json`.  in the raw logs:
```
Traceback (most recent call last):
1470
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
1471
    "__main__", fname, loader, pkg_name)
1472
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
1473
    exec code in run_globals
1474
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 532, in <module>
1475
    final_result = main()
1476
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 522, in main
1477
    return run(args, file_handler)
1478
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 293, in run
1479
    ks_cmd = ks_util.get_ksonnet_cmd(w.app_dir)
1480
  File "/src/kubeflow/testing/py/kubeflow/testing/ks_util.py", line 46, in get_ksonnet_cmd
1481
    with open(app_yaml_file) as app_yaml:
1482
IOError: [Errno 2] No such file or directory: '/src/kubeflow/kubeflow/testing/workflows/app.yaml'
```

**Comment by gabrielwen** [comment]
this is because we don't clone `kubeflow/kubeflow` but arrikto test needs it in periodic test.
