### ISSUE TITLE
kubeflow-ci-deployment out of quota

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#616]
Reported by @Jeffwan 

```
util.py                     72 INFO     time="2020-03-01T07:05:35Z" level=error msg="Creating kfctl-b2de error: &{Code:RESOURCE_ERROR Location:/deployments/kfctl-b2de/resources/kfctl-b2de-ip
 Message:{\"ResourceType\":\"compute.v1.globalAddress\",\"ResourceErrorCode\":\"QUOTA_EXCEEDED\",\"ResourceErrorMessage\":\"Quota 'STATIC_ADDRESSES' exceeded.  Limit: 100.0 globally.\"} Forc
eSendFields:[] NullFields:[]}" filename="gcp/gcp.go:386"
```

**Comment by jlewi** [comment]
Following the playbook.
https://github.com/kubeflow/testing/blob/master/playbook.md#gcp-quota-errors

```
gcloud --project=kubeflow-ci-deployment deployment-manager deployments list --format="table(name,insertTime:sort=1)" 
NAME                         INSERT_TIME
deployapp                    2019-04-26T15:35:43.692-07:00
kftest-0628-1842-storage     2019-06-28T18:26:31.074-07:00
apps-storage                 2019-09-18T16:04:09.441-07:00
apps                         2019-09-18T16:04:10.001-07:00
myapp2-storage               2019-09-30T14:07:32.639-07:00
myapp2                       2019-09-30T14:07:33.214-07:00
kfbeta-storage               2019-10-17T14:06:01.072-07:00
kf-latest-storage            2019-12-05T12:54:59.137-08:00
kfctl-56e3-storage           2020-01-28T10:23:05.203-08:00
kfctl-56e3                   2020-01-28T10:23:05.731-08:00
kfctl-88ea-storage           2020-01-28T11:28:08.147-08:00
kfctl-88ea                   2020-01-28T11:28:08.652-08:00
kfctl-8be3-storage           2020-01-28T18:02:21.027-08:00
kfctl-8be3                   2020-01-28T18:02:21.545-08:00
kfctl-142c-storage           2020-01-29T04:38:19.071-08:00
kfctl-142c                   2020-01-29T04:38:19.620-08:00
kfctl-5cb5-storage           2020-01-29T04:38:27.232-08:00
kfctl-5cb5                   2020-01-29T04:38:27.753-08:00
kfctl-d253-storage           2020-01-29T04:38:56.880-08:00
kfctl-d253                   2020-01-29T04:38:57.394-08:00
kfctl-8aee-storage           2020-01-29T04:42:55.813-08:00
kfctl-8aee                   2020-01-29T04:42:56.344-08:00
kfctl-db94-storage           2020-01-29T04:43:59.540-08:00
kfctl-db94                   2020-01-29T04:44:00.059-08:00
kfctl-6534-storage           2020-01-29T05:20:51.804-08:00
kfctl-6534                   2020-01-29T05:20:52.338-08:00
kfctl-3fac-storage           2020-01-29T05:21:51.872-08:00
kfctl-3fac                   2020-01-29T05:21:52.403-08:00
kfctl-3db4-storage           2020-01-29T05:22:30.336-08:00
kfctl-3db4                   2020-01-29T05:22:30.899-08:00
kfctl-5f2c-storage           2020-01-29T06:16:42.044-08:00
kfctl-5f2c                   2020-01-29T06:16:42.581-08:00
kfctl-a0ad-storage           2020-01-29T06:28:59.466-08:00
kfctl-a0ad                   2020-01-29T06:28:59.989-08:00
kfctl-0067-storage           2020-01-29T06:38:11.274-08:00
kfctl-0067                   2020-01-29T06:38:11.924-08:00
kfctl-6c71-storage           2020-01-29T06:59:36.025-08:00
kfctl-6c71                   2020-01-29T06:59:36.561-08:00
kfctl-2050-storage           2020-01-29T07:04:07.719-08:00
kfctl-2050                   2020-01-29T07:04:08.249-08:00
kfctl-25ac-storage           2020-01-29T07:59:22.186-08:00
kfctl-25ac                   2020-01-29T07:59:22.712-08:00
kfctl-43fe-storage           2020-01-29T08:02:59.930-08:00
kfctl-43fe                   2020-01-29T08:03:00.459-08:00
kfctl-2eae-storage           2020-01-29T08:03:55.531-08:00
kfctl-2eae                   2020-01-29T08:03:56.365-08:00
kf-master-0129-6c3-storage   2020-01-29T20:19:59.441-08:00
kf-master-0129-71f-storage   2020-01-29T21:58:25.926-08:00
kf-master-0129-0d0-storage   2020-01-29T23:02:33.272-08:00
kf-master-0129-376-storage   2020-01-29T23:10:35.450-08:00
kf-v1-01292337-8aa-storage   2020-01-29T23:37:49.691-08:00
kf-v1-01292350-51a-storage   2020-01-29T23:51:39.444-08:00
kf-v1-01292356-66d-storage   2020-01-29T23:56:44.232-08:00
kfctl-eb1b-storage           2020-01-30T04:45:57.345-08:00
kfctl-eb1b                   2020-01-30T04:45:57.892-08:00
kfctl-5d7c-storage           2020-01-30T12:18:15.276-08:00
kfctl-5d7c                   2020-01-30T12:18:15.780-08:00
kfctl-d5eb-storage           2020-01-30T14:08:03.257-08:00
kfctl-d5eb                   2020-01-30T14:08:03.755-08:00
kfctl-e47b-storage           2020-01-31T19:02:28.249-08:00
kfctl-e47b                   2020-01-31T19:02:28.754-08:00
kf-master-0203-64f-storage   2020-02-03T07:00:22.423-08:00
kfctl-5977-storage           2020-02-03T10:42:13.195-08:00
kfctl-5977                   2020-02-03T10:42:13.686-08:00
kfctl-ca9f-storage           2020-02-03T13:45:38.210-08:00
kfctl-ca9f                   2020-02-03T13:45:38.697-08:00
kfctl-f07e-storage           2020-02-04T15:53:35.942-08:00
kfctl-f07e                   2020-02-04T15:53:36.464-08:00
kfctl-7ec5-storage           2020-02-05T05:03:18.377-08:00
kfctl-7ec5                   2020-02-05T05:03:18.892-08:00
kfctl-cb49-storage           2020-02-05T18:51:26.861-08:00
kfctl-cb49                   2020-02-05T18:51:27.363-08:00
kfctl-dd04-storage           2020-02-06T09:13:40.763-08:00
kfctl-dd04                   2020-02-06T09:13:41.284-08:00
kfctl-ba81-storage           2020-02-06T10:43:17.917-08:00
kfctl-ba81                   2020-02-06T10:43:18.476-08:00
kfctl-2b11-storage           2020-02-06T14:59:19.366-08:00
kfctl-2b11                   2020-02-06T14:59:19.824-08:00
kfctl-b952-storage           2020-02-08T13:11:34.736-08:00
kfctl-b952                   2020-02-08T13:11:35.268-08:00
kfctl-98c3-storage           2020-02-10T04:44:53.899-08:00
kfctl-98c3                   2020-02-10T04:44:54.395-08:00
kfctl-3a1c-storage           2020-02-10T04:45:03.544-08:00
kfctl-3a1c                   2020-02-10T04:45:04.029-08:00
kfctl-c485-storage           2020-02-10T05:14:36.597-08:00
kfctl-c485                   2020-02-10T05:14:37.150-08:00
kfctl-1c10-storage           2020-02-10T14:43:37.591-08:00
kfctl-1c10                   2020-02-10T14:43:38.108-08:00
kfctl-a01e-storage           2020-02-11T02:37:56.428-08:00
kfctl-a01e                   2020-02-11T02:37:56.938-08:00
kfctl-0c64-storage           2020-02-11T02:38:01.457-08:00
kfctl-0c64                   2020-02-11T02:38:01.957-08:00
kf-vmaster-0212-bde-storage  2020-02-11T16:21:57.618-08:00
kf-vmaster-0212-bde          2020-02-11T16:21:58.132-08:00
kfctl-144c-storage           2020-02-11T22:51:13.179-08:00
kfctl-144c                   2020-02-11T22:51:13.698-08:00
kfctl-5e32-storage           2020-02-12T10:49:34.530-08:00
kfctl-5e32                   2020-02-12T10:49:35.076-08:00
kfctl-09b3-storage           2020-02-13T01:04:11.259-08:00
kfctl-09b3                   2020-02-13T01:04:11.832-08:00
kfctl-29f2-storage           2020-02-13T14:58:49.700-08:00
kfctl-29f2                   2020-02-13T14:58:50.238-08:00
kfctl-2334-storage           2020-02-13T15:51:57.123-08:00
kfctl-2334                   2020-02-13T15:51:57.716-08:00
kfctl-08ec-storage           2020-02-15T19:08:46.851-08:00
kfctl-08ec                   2020-02-15T19:08:47.369-08:00
kfctl-a8ae-storage           2020-02-16T21:17:21.638-08:00
kfctl-a8ae                   2020-02-16T21:17:22.181-08:00
kfctl-87dc-storage           2020-02-16T22:01:31.347-08:00
kfctl-87dc                   2020-02-16T22:01:31.867-08:00
kfctl-5898-storage           2020-02-16T22:36:27.925-08:00
kfctl-5898                   2020-02-16T22:36:28.463-08:00
kfctl-550b-storage           2020-02-17T14:43:10.784-08:00
kfctl-550b                   2020-02-17T14:43:11.324-08:00
kfctl-04ad-storage           2020-02-17T15:04:03.581-08:00
kfctl-04ad                   2020-02-17T15:04:04.182-08:00
kfctl-4339-storage           2020-02-17T15:30:23.494-08:00
kfctl-4339                   2020-02-17T15:30:24.034-08:00
kfctl-665f-storage           2020-02-17T16:48:00.727-08:00
kfctl-665f                   2020-02-17T16:48:01.276-08:00
kfctl-9175-storage           2020-02-17T17:17:46.297-08:00
kfctl-9175                   2020-02-17T17:17:47.183-08:00
kfctl-a19d-storage           2020-02-17T19:40:52.476-08:00
kfctl-a19d                   2020-02-17T19:40:52.988-08:00
kfctl-5d05-storage           2020-02-19T11:49:20.824-08:00
kfctl-5d05                   2020-02-19T11:49:21.369-08:00
kfctl-5374-storage           2020-02-22T21:50:29.321-08:00
kfctl-5374                   2020-02-22T21:50:29.854-08:00
kfctl-940f-storage           2020-02-25T16:02:03.007-08:00
kfctl-940f                   2020-02-25T16:02:03.543-08:00
kfctl-40de-storage           2020-02-25T16:02:09.421-08:00
kfctl-40de                   2020-02-25T16:02:09.977-08:00
kfctl-acf7-storage           2020-02-25T20:05:04.445-08:00
kfctl-acf7                   2020-02-25T20:05:04.988-08:00
kf-v1-0226-6ce-storage       2020-02-25T23:31:36.463-08:00
kf-v1-0226-6ce               2020-02-25T23:31:37.324-08:00
kf-master-0227-890-storage   2020-02-27T07:54:27.194-08:00
kf-master-0227-890           2020-02-27T07:54:27.757-08:00
kfctl-93c0-storage           2020-02-27T15:16:27.512-08:00
kfctl-93c0                   2020-02-27T15:16:28.176-08:00
kfctl-4af3-storage           2020-02-27T16:53:32.150-08:00
kfctl-4af3                   2020-02-27T16:53:33.020-08:00
kfctl-f5ab-storage           2020-02-27T16:56:27.945-08:00
kfctl-f5ab                   2020-02-27T16:56:28.548-08:00
kfctl-8abb-storage           2020-02-27T17:17:42.055-08:00
kfctl-8abb                   2020-02-27T17:17:42.862-08:00
kfctl-3d14-storage           2020-02-27T20:56:18.170-08:00
kfctl-3d14                   2020-02-27T20:56:18.698-08:00
kfctl-004d-storage           2020-02-27T22:05:37.748-08:00
kfctl-004d                   2020-02-27T22:05:38.533-08:00
kfctl-a238-storage           2020-02-27T22:09:08.775-08:00
kfctl-a238                   2020-02-27T22:09:09.374-08:00
kfctl-e5a9-storage           2020-02-27T22:09:14.894-08:00
kfctl-e5a9                   2020-02-27T22:09:15.505-08:00
kfctl-9d50-storage           2020-02-27T22:10:05.291-08:00
kfctl-9d50                   2020-02-27T22:10:05.913-08:00
kfctl-f065-storage           2020-02-28T00:33:25.628-08:00
kfctl-f065                   2020-02-28T00:33:26.161-08:00
kfctl-e09b-storage           2020-02-28T02:56:30.709-08:00
kfctl-e09b                   2020-02-28T02:56:31.269-08:00
kfctl-03c4-storage           2020-02-28T03:08:05.939-08:00
kfctl-03c4                   2020-02-28T03:08:06.483-08:00
kfctl-93ca-storage           2020-02-28T04:56:56.474-08:00
kfctl-93ca                   2020-02-28T04:56:57.034-08:00
kfctl-b80f-storage           2020-02-28T06:06:58.651-08:00
kfctl-b80f                   2020-02-28T06:06:59.188-08:00
kfctl-7792-storage           2020-02-28T06:07:13.248-08:00
kfctl-7792                   2020-02-28T06:07:13.793-08:00
kfctl-a061-storage           2020-02-28T06:07:18.557-08:00
kfctl-a061                   2020-02-28T06:07:19.101-08:00
kfctl-bd74-storage           2020-02-28T09:34:24.987-08:00
kfctl-bd74                   2020-02-28T09:34:25.541-08:00
kfctl-c371-storage           2020-02-28T09:36:06.205-08:00
kfctl-c371                   2020-02-28T09:36:06.758-08:00
kfctl-c41c-storage           2020-02-28T12:58:42.436-08:00
kfctl-c41c                   2020-02-28T12:58:42.980-08:00
kfctl-d67e-storage           2020-02-28T14:08:10.071-08:00
kfctl-d67e                   2020-02-28T14:08:10.623-08:00
kfctl-740f-storage           2020-02-28T14:09:53.763-08:00
kfctl-740f                   2020-02-28T14:09:54.314-08:00
kfctl-a0f0-storage           2020-02-28T14:09:59.001-08:00
kfctl-a0f0                   2020-02-28T14:09:59.566-08:00
kfctl-b1f8-storage           2020-02-28T14:54:41.831-08:00
kfctl-b1f8                   2020-02-28T14:54:42.411-08:00
kfctl-40f2-storage           2020-02-28T15:03:59.207-08:00
kfctl-40f2                   2020-02-28T15:03:59.878-08:00
kfctl-5131-storage           2020-02-28T16:48:46.587-08:00
kfctl-5131                   2020-02-28T16:48:47.165-08:00
kfctl-4104-storage           2020-02-28T17:34:24.493-08:00
kfctl-4104                   2020-02-28T17:34:25.134-08:00
kfctl-f09d-storage           2020-02-28T20:59:14.110-08:00
kfctl-f09d                   2020-02-28T20:59:14.972-08:00
kfctl-bcff-storage           2020-02-28T22:08:10.742-08:00
kfctl-bcff                   2020-02-28T22:08:11.305-08:00
kfctl-bf93-storage           2020-02-28T22:11:43.485-08:00
kfctl-bf93                   2020-02-28T22:11:44.057-08:00
kfctl-440c-storage           2020-02-28T22:12:26.986-08:00
kfctl-440c                   2020-02-28T22:12:27.517-08:00
kfctl-31b3-storage           2020-02-29T04:22:34.305-08:00
kfctl-31b3                   2020-02-29T04:22:34.903-08:00
kfctl-1c59-storage           2020-02-29T05:02:32.482-08:00
kfctl-1c59                   2020-02-29T05:02:33.007-08:00
kfctl-8c4b-storage           2020-02-29T06:08:07.883-08:00
kfctl-8c4b                   2020-02-29T06:08:08.482-08:00
kfctl-c49c-storage           2020-02-29T06:14:02.367-08:00
kfctl-c49c                   2020-02-29T06:14:02.921-08:00
kfctl-fe39-storage           2020-02-29T06:14:05.962-08:00
kfctl-fe39                   2020-02-29T06:14:06.516-08:00
kfctl-ad74-storage           2020-02-29T10:33:18.104-08:00
kfctl-ad74                   2020-02-29T10:33:18.931-08:00
kfctl-257d-storage           2020-02-29T13:02:28.618-08:00
kfctl-257d                   2020-02-29T13:02:29.183-08:00
kfctl-7e00-storage           2020-02-29T14:11:08.447-08:00
kfctl-7e00                   2020-02-29T14:11:09.056-08:00
kfctl-3007-storage           2020-02-29T14:11:54.538-08:00
kfctl-3007                   2020-02-29T14:11:55.101-08:00
kfctl-0bf2-storage           2020-02-29T14:11:59.349-08:00
kfctl-0bf2                   2020-02-29T14:11:59.910-08:00
kfctl-056d-storage           2020-02-29T21:03:38.435-08:00
kfctl-056d                   2020-02-29T21:03:39.013-08:00
kfctl-ffaf-storage           2020-02-29T22:13:11.383-08:00
kfctl-ffaf                   2020-02-29T22:13:11.936-08:00
kfctl-b2ab-storage           2020-02-29T22:13:43.952-08:00
kfctl-b2ab                   2020-02-29T22:13:44.445-08:00
kfctl-fca0-storage           2020-02-29T22:13:45.274-08:00
kfctl-fca0                   2020-02-29T22:13:45.996-08:00
kfctl-b2de-storage           2020-02-29T23:02:43.236-08:00
kfctl-b2de                   2020-02-29T23:02:43.790-08:00
kfctl-1192-storage           2020-03-01T00:27:29.227-08:00
kfctl-1192                   2020-03-01T00:27:29.889-08:00
kfctl-4d9a-storage           2020-03-01T00:28:36.648-08:00
kfctl-4d9a                   2020-03-01T00:28:37.241-08:00
kfctl-b81b-storage           2020-03-01T00:28:48.953-08:00
kfctl-b81b                   2020-03-01T00:28:49.494-08:00
kfctl-faa9-storage           2020-03-01T00:57:24.392-08:00
kfctl-faa9                   2020-03-01T00:57:25.198-08:00
kfctl-4ea0-storage           2020-03-01T04:28:34.493-08:00
kfctl-4ea0                   2020-03-01T04:28:34.997-08:00
kfctl-5a1b-storage           2020-03-01T04:28:41.556-08:00
kfctl-5a1b                   2020-03-01T04:28:42.095-08:00
kfctl-3479-storage           2020-03-01T04:28:50.685-08:00
kfctl-3479                   2020-03-01T04:28:51.231-08:00
kfctl-4fb9-storage           2020-03-01T05:02:53.458-08:00
kfctl-4fb9                   2020-03-01T05:02:54.089-08:00
kfctl-e31d-storage           2020-03-01T06:13:28.640-08:00
kfctl-e31d                   2020-03-01T06:13:29.690-08:00
kfctl-c99a-storage           2020-03-01T06:13:48.458-08:00
kfctl-c99a                   2020-03-01T06:13:48.999-08:00
kfctl-3b79-storage           2020-03-01T06:14:50.332-08:00
kfctl-3b79                   2020-03-01T06:14:51.212-08:00
kfctl-3a71-storage           2020-03-01T08:30:28.249-08:00
kfctl-3a71                   2020-03-01T08:30:28.837-08:00
kfctl-a911-storage           2020-03-01T08:30:41.213-08:00
kfctl-a911                   2020-03-01T08:30:41.768-08:00
kfctl-7b8f-storage           2020-03-01T08:30:42.911-08:00
kfctl-7b8f                   2020-03-01T08:30:43.452-08:00
kfctl-2353-storage           2020-03-01T12:32:51.321-08:00
kfctl-2353                   2020-03-01T12:32:51.843-08:00
kfctl-e5c7-storage           2020-03-01T12:34:54.796-08:00
kfctl-e5c7                   2020-03-01T12:34:55.446-08:00
kfctl-5dd9-storage           2020-03-01T12:35:07.034-08:00
kfctl-5dd9                   2020-03-01T12:35:07.547-08:00
kfctl-976a-storage           2020-03-01T14:14:22.786-08:00
kfctl-976a                   2020-03-01T14:14:23.337-08:00
kfctl-498b-storage           2020-03-01T14:17:04.381-08:00
kfctl-498b                   2020-03-01T14:17:04.915-08:00
kfctl-6ea6-storage           2020-03-01T14:18:26.232-08:00
kfctl-6ea6                   2020-03-01T14:18:26.790-08:00
kfctl-f291-storage           2020-03-01T16:32:42.128-08:00
kfctl-f291                   2020-03-01T16:32:42.723-08:00
kfctl-f6bc-storage           2020-03-01T16:32:50.830-08:00
kfctl-f6bc                   2020-03-01T16:32:51.375-08:00
kfctl-e66a-storage           2020-03-01T16:33:09.175-08:00
kfctl-e66a                   2020-03-01T16:33:09.735-08:00
```

So looks like lots of deployments not being GC'd

**Comment by jlewi** [comment]
Here are the logs from the cleanup job.
Most of the deployments are skipped.

```
INFO|2020-03-02T04:00:25|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|1068| Skipping deployment kfctl-5dd9; its missing the label
INFO|2020-03-02T04:00:25|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|1073| Skipping deployment kfctl-5dd9; it is not an auto-deployed instance
INFO|2020-03-02T04:00:25|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|1068| Skipping deployment kfctl-5dd9-storage; its missing the label
INFO|2020-03-02T04:00:25|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|1073| Skipping deployment kfctl-5dd9-storage; it is not an auto-deployed instance
INFO|2020-03-02T04:00:25|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|1068| Skipping deployment kfctl-5e32; its missing the label
```

[cleanup-ci-kubeflow-ci-deployment-1583121600-np622.logs.txt](https://github.com/kubeflow/testing/files/4273395/cleanup-ci-kubeflow-ci-deployment-1583121600-
np622.logs.txt)

**Comment by jlewi** [comment]
That is working is intended since that is coming from the section to cleanup auto deployments. 

An exception occurred while trying to cleanup deployments.

```
NFO|2020-03-02T04:00:26|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|1118| Cleanup deployments
ERROR|2020-03-02T04:00:26|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|1264| 'generator' object has no attribute 'get'
Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 1262, in cleanup_all
    op(args)
  File "/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py", line 1125, in cleanup_deployments
    for d in deployments.get("deployments", []):
AttributeError: 'generator' object has no attribute 'get'
```

**Comment by jlewi** [comment]
Fixed the code and ran a cleanup.


```
gcloud --project=kubeflow-ci-deployment compute addresses list
NAME                                                 ADDRESS/RANGE   TYPE      PURPOSE  NETWORK  REGION  SUBNET  STATUS
apps-ip                                              35.244.163.146  EXTERNAL                                    IN_USE
k8s-fw-istio-system-envoy-ingress--1d7f42130cac1b03  35.244.207.40   EXTERNAL                                    RESERVED
k8s-fw-istio-system-envoy-ingress--8aeac172f51b6edd  35.244.163.151  EXTERNAL                                    RESERVED
k8s-fw-kubeflow-envoy-ingress--d5384c3095008610      35.190.53.179   EXTERNAL                                    RESERVED
myapp2-ip                                            35.201.82.85    EXTERNAL                                    IN_USE
```

And deployments

```
gcloud --project=kubeflow-ci-deployment deployment-manager deployments list --format="table(name,insertTime:sort=1)" 
NAME                        INSERT_TIME
deployapp                   2019-04-26T15:35:43.692-07:00
kftest-0628-1842-storage    2019-06-28T18:26:31.074-07:00
apps-storage                2019-09-18T16:04:09.441-07:00
apps                        2019-09-18T16:04:10.001-07:00
myapp2-storage              2019-09-30T14:07:32.639-07:00
myapp2                      2019-09-30T14:07:33.214-07:00
kfbeta-storage              2019-10-17T14:06:01.072-07:00
kf-latest-storage           2019-12-05T12:54:59.137-08:00
kf-v1-0226-6ce-storage      2020-02-25T23:31:36.463-08:00
kf-master-0227-890-storage  2020-02-27T07:54:27.194-08:00
kfctl-0577-storage          2020-03-01T20:18:34.328-08:00
kfctl-0577                  2020-03-01T20:18:34.911-08:00
```

So quota should be fixed.
