### ISSUE TITLE
Issues with the `get_kf_testing_cluster`when using `get-credentials` for e2e test development for the mpi-operator. 

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/testing#656]
I am working with setting up [e2e test for the mpi-operator](https://github.com/kubeflow/mpi-operator/pull/244).  I managed to get it to work last weekend but when I tried to continue the work today I get issues with the part where [I try to get the credentials](https://github.com/NikeNano/mpi-operator/blob/fb2da145d10a05e4d846b400952eaecb327e4a16/py/kubeflow/mpi-operator/create_e2e_workflow.py#L325), most of the code is copied form the kubeflow/examples repo. 

I can't see any breaking changes and sadly dont understand the code enough to know how to continue to debug it.

Logs from argo: 
```W
INFO|2020-05-08T07:51:03|/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/get_kf_testing_cluster.py|232| Calling get_cre
dential - this call needs gcloud client CLI.
INFO|2020-05-08T07:51:03|/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/util.py|826| GOOGLE_APPLICATION_CREDENTIALS is
 set; configuring gcloud to use service account.
INFO|2020-05-08T07:51:03|/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/util.py|46| Running: gcloud auth activate-serv
ice-account --key-file=/secret/gcp-credentials/key.json
cwd=None
INFO|2020-05-08T07:51:03|/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/util.py|61| Subprocess output:
INFO|2020-05-08T07:51:04|/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/util.py|72| Activated service account credenti
als for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
WARNING|2020-05-08T07:51:05|/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery_cache/__init__.py|44| file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
 File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
   from google.appengine.api import memcache
ImportError: No module named 'google.appengine'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
   from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
   from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
   from . import file_cache
 File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
   'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO|2020-05-08T07:51:05|/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery.py|274| URL being requested: GET https://www.googleapis.com/discovery/v1/apis/deploymentmanager/v2/rest
INFO|2020-05-08T07:51:05|/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery.py|868| URL being requested: GET https://www.googleapis.com/deploymentmanager/v2/projects/kubeflow-ci-depl
oyment/global/deployments?alt=json&filter=
INFO|2020-05-08T07:51:05|/usr/local/lib/python3.5/dist-packages/oauth2client/transport.py|157| Attempting refresh to obtain initial access_token
INFO|2020-05-08T07:51:05|/usr/local/lib/python3.5/dist-packages/oauth2client/client.py|777| Refreshing access_token
INFO|2020-05-08T07:51:05|/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery.py|868| URL being requested: GET https://www.googleapis.com/deploymentmanager/v2/projects/kubeflow-ci-depl
oyment/global/deployments/kf-master-0508-f18/resources/kf-master-0508-f18?alt=json
Traceback (most recent call last):
 File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
   "__main__", mod_spec)
 File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/get_kf_testing_cluster.py", line 287, in <module>
   main()
 File "/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/get_kf_testing_cluster.py", line 284, in main
   args.func(args)
 File "/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/get_kf_testing_cluster.py", line 233, in get_credential
   get_latest_credential(project=args.project, base_name=args.base_name)
 File "/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/get_kf_testing_cluster.py", line 207, in get_latest_credential
   base_name=base_name, field="all")
 File "/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/get_kf_testing_cluster.py", line 193, in get_latest
   return get_deployment(project, base_name, testing_label, http=http, field=field)
 File "/mnt/test-data-volume/kubeflow-mpi-operator-presubmit-e2e-mpi-244-fb2da14-2944-a38d/src/kubeflow/testing/py/kubeflow/testing/get_kf_testing_cluster.py", line 166, in get_deployment
   raise LookupError("No deployments found...")
LookupError: No deployments found...```

Would be great if I could get some help in the right direction related to the testing :)

**Comment by NikeNano** [comment]
After further testing i got it to work by adding the cluster pattern : 
```
kwargs:
    cluster_pattern: kf-v1-(?!n\d\d)
```

Should it be needed to add the cluster pattern? As far as I can see there are some use cases which use the default: 

https://github.com/kubeflow/examples/blob/0609ad47388abba37d074736014a239d0839a951/prow_config.yaml#L50

**Comment by NikeNano** [comment]
Has the label changed in some way for the "default" cluster?

**Comment by jlewi** [comment]
@NikeNano those clusters are auto-deployed periodically and so the pattern will depend on which auto-deployed cluster you want to use. There is more information here:
https://github.com/kubeflow/testing/tree/master/test-infra/auto-deploy

**Comment by NikeNano** [comment]
> @NikeNano those clusters are auto-deployed periodically and so the pattern will depend on which auto-deployed cluster you want to use. There is more information here:
> https://github.com/kubeflow/testing/tree/master/test-infra/auto-deploy

Thanks for the answer! Also replied with a longer comment to your answere on the PR in kubeflow/mpi-operator
