### ISSUE TITLE
Tekton runs fail in periodic jobs because no repo under test

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#696]
Failed run of gcp blueprints periodic

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-gcp-blueprints-master/1273672453511450625

The problem is we are trying to substitute in the URL for the repo being tested but there is no repo being test in periodic.

```
Terminated (Error - on pipeline gcp-kf-ready INFO|2020-06-18T17:42:39|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|147| Reading Tekton PipelineRun config: gcp-kf-ready- INFO|2020-06-18T17:42:39|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|168| Writing Tekton param: artifacts-gcs -> gs://kubernetes-jenkins/logs/kubeflow-gcp-blueprints-master/1273672453511450625 INFO|2020-06-18T17:42:39|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|168| Writing Tekton param: testing-cluster-location -> us-central1 INFO|2020-06-18T17:42:39|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|168| Writing Tekton param: junit-path -> artifacts/junit_gcp-kf-ready- INFO|2020-06-18T17:42:39|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|168| Writing Tekton param: test-target-name -> gcp-kf-ready INFO|2020-06-18T17:42:39|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|168| Writing Tekton param: testing-cluster-pattern -> kf-vbp-.* Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 614, in <module> final_result = main() File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 604, in main return run(args, file_handler) File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 382, in run pull_revision) File "/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py", line 212, in __init__ pull_revision) File "/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py", line 197, in load_tekton_run "a git resource whose URL is {0}".format(repo_url))) ValueError: The TektonPipelineRun is missing a pipeline git resource that matches the repo being tested by prow. The pipeline parameters must include a git resource whose URL is https://github.com/kubeflow/gcp-blueprints.git ) at 2020-06-18 17:42:39 +0000 UTC with exit code 1
```

**Comment by jlewi** [comment]
Formatted version of the logs.

[0f6f35a9-b18b-11ea-a6be-7aface92fb81.log.txt](https://github.com/kubeflow/testing/files/4801499/0f6f35a9-b18b-11ea-a6be-7aface92fb81.log.txt)
